// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxjapbzccqipozybzkwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14amFwYnpjY3FpcG96eWJ6a3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwOTY5ODQsImV4cCI6MjA3NDY3Mjk4NH0.cILDF9Dh7hNib8EikRQxGKSZjgYoWJVKYwxt4IRlhzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});